## 2. Gram-Schmidt 

### 2.1. 개요
  
  - 직교화(orthogonalization)는 벡터공간에서 서로 직교하는 정규 기저1(orthonormal basis)를 찾는 과정으로서 수치적 선형대수가 활용되는 대부분의 분야에서 빈번하게 사용됨.
  
  - Gram-Schmidt 과정은 직교화의 방법 중 하나로 다음과 같은 알고리즘으로 진행.
  
    <img src = "images/image12.png" width="70%" height="70%">

    <img src = "images/image13.png" width="70%" height="70%">

  - 이를 전개하여 표현하면 다음곽 같음.

  $$\bf{u} _1 = \bf{v} _1$$
  
  $$\bf{u} _2 = \bf{v} _2 - \frac{\langle \bf{v _2}, \bf{u}_{1} \rangle}{\left\| \bf{u}_{1} \right\| ^{2}} \bf{u}_{1} $$

  $$\bf{u} _3 = \bf{v} _3 - \frac{\langle \bf{v _3}, \bf{u}_{2} \rangle}{\left\| \bf{u}_{2} \right\| ^{2}} \bf{u}_{2}-\frac{\langle \bf{v _3}, \bf{u}_{1} \rangle}{\left\| \bf{u}_{1} \right\| ^{2}} \bf{u}_{1}$$
    
  $$ \vdots $$
  
  $$ \bf{u} _n 
    = \bf{v} _n - \frac{\langle \bf{v _n}, \bf{u}_{n-1} \rangle}{\left\| \bf{u}_{n-1} \right\| ^{2}} \bf{u}_{n-1}
    - \frac{\langle \bf{v _n}, \bf{u}_{n-2} \rangle}{\left\| \bf{u}_{n-2} \right\| ^{2}} \bf{u}_{n-2}
    - \cdots 
    - \frac{\langle \bf{v _n}, \bf{u}_{1} \rangle}{\left\| \bf{u}_{1} \right\| ^{2}} \bf{u}_{1}$$

  - 2차원 벡터에 대한 Gram-Schmidt 과정
  
  <img src = "images/image14.png">


### 2.2. QR 분해

  - 다음과 같이 $\bf{A}$를 분해

  $$ \bf{A} = \bf{QR} $$

  - 여기서 $\bf{Q}$의 열벡터는 $\bf{A}$의 열벡터가 span하는 공간 $S$의 직교 기저 벡터이며, $\bf{R}$는 Upper triangular matrix임
  
  - $\bf{A}$ 의 열벡터 ${ \bf{a}_i}$ 들은 Gram-Schmidt 과정을 거쳐 얻어진 정규 직교 벡터 ${ (\bf{u}_1, \bf{u}_2, \cdots, \bf{u}_n)}$ 에 대해 다음을 만족
  
  $$ \bf{a} _i
  = \langle \bf{a} _i, \bf{u}_{1} \rangle \bf{u}_{1} + 
  \langle \bf{a} _i, \bf{u}_{2} \rangle \bf{u}_{2} + \cdots +
  \langle \bf{a} _i, \bf{u}_{n} \rangle \bf{u}_{n} $$

In [1]:
import numpy as np

# 10개의 20차원 벡터
N = 10
D = 20
v = np.random.rand(D, N)

np.save("v", v)

In [2]:
# QR 분해 : Q의 열벡터가 정규기저벡터
import numpy as np

v = np.load("v.npy")
print(v)
Q, R = np.linalg.qr(v)
print(Q)
print(R)
print(np.linalg.norm(Q[0]))

[[0.86863355 0.58299428 0.46334201 0.1129311  0.49865865 0.42828865
  0.35825733 0.51876235 0.40760652 0.38975693]
 [0.57071988 0.29461895 0.89863903 0.48336989 0.5585511  0.96661326
  0.61693177 0.67817002 0.76688583 0.4652491 ]
 [0.30213836 0.43944749 0.76217374 0.69046442 0.06828829 0.38575618
  0.43737357 0.58882244 0.84946302 0.52906997]
 [0.8865924  0.99034356 0.45936386 0.19323491 0.68024431 0.88781502
  0.20150281 0.8638305  0.05777996 0.28406185]
 [0.11457037 0.11363469 0.23243618 0.6552648  0.32928878 0.35317339
  0.58643029 0.0751571  0.97998494 0.48855539]
 [0.07205749 0.02660716 0.38818587 0.14426921 0.31053729 0.15033864
  0.72428203 0.86570744 0.28561209 0.23140311]
 [0.66272451 0.56557793 0.22442188 0.11357181 0.01187908 0.97193387
  0.61121036 0.59430521 0.73933296 0.80969639]
 [0.65902663 0.35895725 0.54488406 0.88116016 0.91100308 0.48954537
  0.96766671 0.57502361 0.06064238 0.37728553]
 [0.10362852 0.75151492 0.59402596 0.98459476 0.78705138 0.03545229
  0.46596731

1. 순차코드
   
  - 열벡터를 행벡터로 전환
  - 메모리 접근이 효율적임

In [3]:
import numpy as np

V = np.transpose(v).copy()
print(V)
for j in range (N) :
    for i in range (j) :
        coef = -np.dot(V[i], V[j])
        V[j] = V[j] + coef * V[i]
    coef = np.linalg.norm(V[j])
    V[j] = V[j] / coef

print(V)

[[0.86863355 0.57071988 0.30213836 0.8865924  0.11457037 0.07205749
  0.66272451 0.65902663 0.10362852 0.98794046 0.36931823 0.49335473
  0.27539755 0.8550721  0.79802442 0.37082437 0.54381032 0.68148416
  0.77622214 0.18331317]
 [0.58299428 0.29461895 0.43944749 0.99034356 0.11363469 0.02660716
  0.56557793 0.35895725 0.75151492 0.43009026 0.45691766 0.15798381
  0.03481153 0.82924665 0.58200161 0.46838115 0.78735045 0.75847106
  0.64642594 0.4559173 ]
 [0.46334201 0.89863903 0.76217374 0.45936386 0.23243618 0.38818587
  0.22442188 0.54488406 0.59402596 0.26734072 0.79755689 0.60708872
  0.40928766 0.90175651 0.04778105 0.99608125 0.80771431 0.83264875
  0.85384363 0.13269993]
 [0.1129311  0.48336989 0.69046442 0.19323491 0.6552648  0.14426921
  0.11357181 0.88116016 0.98459476 0.76206251 0.78873866 0.41729031
  0.00774181 0.92831012 0.08623342 0.28982734 0.04634215 0.52561311
  0.72497075 0.77650111]
 [0.49865865 0.5585511  0.06828829 0.68024431 0.32928878 0.31053729
  0.01187908 0.9

2. 병렬코드

  - 의존성 분석
    - $u_i$들은 순차적으로 계산됨 : $u_i$를 위해 $u_{i-1}, \cdots, u_{1}$이 필요
    - $u_i, v_i$의 각 $i$ 성분 계산은 독립적임 : 이를 나누어 계산하며 벡터 분할과 동일
  
  <img src = "images/image03.png">

In [4]:
%%writefile gs.py
import numpy as np
from mpi4py import MPI
from tools import para_range

N = 3
D = 9

comm = MPI.COMM_WORLD

size = comm.Get_size()
rank = comm.Get_rank()

if rank == 0 : 
    v = np.load("v.npy")
    V = np.transpose(v).copy()
else :
    V = np.empty((N, D), dtype = np.float64)

ista, iend = para_range(D, size, rank)

chunk = iend - ista + 1

# Scatterv에 필요한 cnts와 disp 계산
cnts = comm.allgather(chunk) #FIX ME
disp = []
for i in range (size) :
    disp.append(sum(cnts[:i])) #FIX ME

V_chunk = np.empty([N, chunk], dtype = np.float64)

# V의 분할. 모든 V[i]에 대한 분할 필요
for i in range (N) :
    comm.Scatterv( (V[i],cnts), V_chunk[i], root = 0) #FIX ME
    
# 분할 계산후 reduction
for j in range (N) :
    for i in range (j) :
        coef = -np.dot(V_chunk[i], V_chunk[j]) #FIX ME
        coef_all = comm.allreduce(coef) #FIX ME
        V_chunk[j] = V_chunk[j] + coef_all * V_chunk[i]
    coef = np.dot(V_chunk[j], V_chunk[j])
    coef_all = comm.allreduce(coef) #FIX ME
    V_chunk[j] = V_chunk[j] / np.sqrt(coef_all)

print(V_chunk)

for i in range (N) :
    comm.Gatherv( V_chunk[i], (V[i],cnts), root = 0)

if rank == 0 :
    print(V)
    


Writing gs.py


In [5]:
! mpirun -np 4 python gs.py

[[ 0.04260732  0.3918665 ]
 [-0.04228082  0.01497127]
 [ 0.36717828 -0.29994426]]
[[ 0.51361974  0.33746451  0.17865327]
 [-0.17962064 -0.22930802  0.23538036]
 [-0.13358518  0.58154157  0.46155099]]
[[ 0.52423873  0.06774502]
 [ 0.31417422  0.02254765]
 [-0.35537706  0.14311282]]
[[ 0.38967995  0.06127515]
 [-0.24118744  0.83687115]
 [ 0.14471683  0.19603966]]
[[ 0.51361974  0.33746451  0.17865327  0.52423873  0.06774502  0.04260732
   0.3918665   0.38967995  0.06127515  0.98794046  0.36931823  0.49335473
   0.27539755  0.8550721   0.79802442  0.37082437  0.54381032  0.68148416
   0.77622214  0.18331317]
 [-0.17962064 -0.22930802  0.23538036  0.31417422  0.02254765 -0.04228082
   0.01497127 -0.24118744  0.83687115  0.43009026  0.45691766  0.15798381
   0.03481153  0.82924665  0.58200161  0.46838115  0.78735045  0.75847106
   0.64642594  0.4559173 ]
 [-0.13358518  0.58154157  0.46155099 -0.35537706  0.14311282  0.36717828
  -0.29994426  0.14471683  0.19603966  0.26734072  0.79755689  0